/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createGitHubUserProfileDtoFromDiscriminatorValue, type GitHubUserProfileDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /github/profile
 */
export interface ProfileRequestBuilder extends BaseRequestBuilder<ProfileRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<GitHubUserProfileDto>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<GitHubUserProfileDto | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const ProfileRequestBuilderUriTemplate = "{+baseurl}/github/profile";
/**
 * Metadata for all the requests in the request builder.
 */
export const ProfileRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: ProfileRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.dev-habit.hateoas+json",
        adapterMethodName: "send",
        responseBodyFactory:  createGitHubUserProfileDtoFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
