/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { PersonalAccessTokenRequestBuilderRequestsMetadata, type PersonalAccessTokenRequestBuilder } from './personalAccessToken/index.js';
// @ts-ignore
import { ProfileRequestBuilderRequestsMetadata, type ProfileRequestBuilder } from './profile/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /github
 */
export interface GithubRequestBuilder extends BaseRequestBuilder<GithubRequestBuilder> {
    /**
     * The personalAccessToken property
     */
    get personalAccessToken(): PersonalAccessTokenRequestBuilder;
    /**
     * The profile property
     */
    get profile(): ProfileRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const GithubRequestBuilderUriTemplate = "{+baseurl}/github";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const GithubRequestBuilderNavigationMetadata: Record<Exclude<keyof GithubRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    personalAccessToken: {
        requestsMetadata: PersonalAccessTokenRequestBuilderRequestsMetadata,
    },
    profile: {
        requestsMetadata: ProfileRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
