/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { serializeStoreGithubAccessTokenDto, type StoreGithubAccessTokenDto } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /github/personal-access-token
 */
export interface PersonalAccessTokenRequestBuilder extends BaseRequestBuilder<PersonalAccessTokenRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<ArrayBuffer>}
     */
     put(body: StoreGithubAccessTokenDto, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<ArrayBuffer | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: StoreGithubAccessTokenDto, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const PersonalAccessTokenRequestBuilderUriTemplate = "{+baseurl}/github/personal-access-token";
/**
 * Metadata for all the requests in the request builder.
 */
export const PersonalAccessTokenRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: PersonalAccessTokenRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.dev-habit.hateoas+json",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
    },
    put: {
        uriTemplate: PersonalAccessTokenRequestBuilderUriTemplate,
        responseBodyContentType: "application/vnd.dev-habit.hateoas+json",
        adapterMethodName: "sendPrimitive",
        responseBodyFactory:  "ArrayBuffer",
        requestBodyContentType: "application/json-patch+json",
        requestBodySerializer: serializeStoreGithubAccessTokenDto,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
